### ISSUE TITLE
Remove dependency on mcrypt

### ISSUE THREAD

**Issue by ruudk** [schmittjoh/JMSPaymentCoreBundle#196]
It's been deprecated in PHP 7.1

http://php.net/manual/en/migration71.deprecated.php

**Comment by ruudk** [comment]
```
Function mcrypt_list_algorithms() is deprecated in /home/app/releases/20161205121224/vendor/jms/payment-core-bundle/JMS/Payment/CoreBundle/Cryptography/MCryptEncryptionService.php on line 49
Deprecated: Function mcrypt_list_algorithms() is deprecated in /home/app/releases/20161205121224/vendor/jms/payment-core-bundle/JMS/Payment/CoreBundle/Cryptography/MCryptEncryptionService.php on line 49
PHP Deprecated:  Function mcrypt_list_modes() is deprecated in /home/app/releases/20161205121224/vendor/jms/payment-core-bundle/JMS/Payment/CoreBundle/Cryptography/MCryptEncryptionService.php on line 53
Deprecated: Function mcrypt_list_modes() is deprecated in /home/app/releases/20161205121224/vendor/jms/payment-core-bundle/JMS/Payment/CoreBundle/Cryptography/MCryptEncryptionService.php on line 53
PHP Deprecated:  Function mcrypt_get_key_size() is deprecated in /home/app/releases/20161205121224/vendor/jms/payment-core-bundle/JMS/Payment/CoreBundle/Cryptography/MCryptEncryptionService.php on line 65
Deprecated: Function mcrypt_get_key_size() is deprecated in /home/app/releases/20161205121224/vendor/jms/payment-core-bundle/JMS/Payment/CoreBundle/Cryptography/MCryptEncryptionService.php on line 65
```

**Comment by regularjack** [comment]
Thanks for reporting this. I had no idea mcrypt was in such bad shape. 

There seem to be [two options](https://paragonie.com/blog/2015/05/if-you-re-typing-word-mcrypt-into-your-code-you-re-doing-it-wrong): 

1. Using OpenSSL, which requires the OpenSSL extension
2. Use [defuse/php-encryption](https://github.com/defuse/php-encryption) which has no dependencies but requires PHP 5.4

In any case, if I'm not mistaken, the change will not be backwards-compatible, so this can only be done for [v2.0](https://github.com/schmittjoh/JMSPaymentCoreBundle/milestone/3).

I'm more in favor of defuse/php-encryption since it has no dependencies, even though it will require us to drop php 5.3 support (it's about time anyway).

What do you think? @ruudk @schmittjoh

**Comment by regularjack** [comment]
Usage of mcrypt within this bundle has now been deprecated in favour of [defuse/php-encryption](https://github.com/defuse/php-encryption), which is now the default encryption provider for new installations. Existing installations keep using mcrypt in order to maintain BC. See the [Change log](https://github.com/schmittjoh/JMSPaymentCoreBundle/blob/master/CHANGELOG.md#130---2017-01-22) for `1.3.0` for more information.

Thanks for reporting this issue.
